name: Update Modrinth project description

on:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  update-modrinth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Update Modrinth project description
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: |
          # Read README.md
          README_CONTENT=$(cat README.md)

          # Replace relative links
          README_CONTENT=$(echo "$README_CONTENT" | \
            sed 's|(/docs/|(https://github.com/caiostoduto/LoginPhaseProxy/raw/main/docs/|g' | \
            sed 's|(/src/|(https://github.com/caiostoduto/LoginPhaseProxy/blob/main/src/|g'
          )

          # Debug
          echo "$README_CONTENT"

          # Escape JSON safely
          JSON_BODY=$(jq -Rn --arg body "$README_CONTENT" '{body: $body}')

          # Send to Modrinth
          curl -X PATCH "https://api.modrinth.com/v2/project/loginphaseproxy" \
            -H "Content-Type: application/json" \
            -H "User-Agent: loginphaseproxy" \
            -H "Authorization: $MODRINTH_TOKEN" \
            --data "$JSON_BODY"
